package com.sunday.tranzsign.domain.service

import com.sunday.tranzsign.domain.entity.AuthStrategy

/**
 * Process and submit the signed transaction challenge to the backend for execution.
 * The service is responsible for handling the communication with the backend API to submit the transaction and receive
 * confirmation of success or failure. It abstracts away the details of the API interaction, allowing the UI layer to simply call this service with the necessary parameters.
 *
 * Transaction metadata like timestamp were skipped for simplicity, but can be added as needed in the future.
 */
interface TransactionService {
    /**
     * Submits the signed transaction challenge to the backend for execution.
     * @param quotationId The unique identifier of the transaction quotation associated with this submission.
     * @param signedChallenge The signed challenge string that was generated by the SignatureService after signing the original challenge.
     * @param authStrategy The authentication strategy used during signing, for audit purposes and potential backend processing logic.
     * @return A boolean indicating whether the transaction submission was successful or not.
     */
    suspend fun submit(
        quotationId: String,
        signedChallenge: String,
        authStrategy: AuthStrategy
    ): Boolean
}